#!/bin/sh

yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install -y openvpn easy-rsa

chmod +x /home/ec2-user/vpn/openvpn-connect.service /home/ec2-user/vpn/openvpn-connect.sh
ln -s /home/ec2-user/vpn/openvpn-connect.service /etc/init.d/openvpn-connect

service openvpn-connect start
