#!/bin/bash

set -e

mkfs -t xfs /dev/sdb
mkdir /data
echo "/dev/sdb    /data    xfs    defaults,nofail    0    2" >> /etc/fstab
mount -a

yum install -y https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat10-10-2.noarch.rpm
sed -i "s/rhel-\$releasever-\$basearch/rhel-latest-x86_64/g" "/etc/yum.repos.d/pgdg-10-redhat.repo"
yum install -y postgresql10 postgresql10-server postgresql10-contrib
repoquery -l postgresql10

mkdir -p /data/pgsql
rm -rf /var/lib/pgsql/10/data
ln -s /data/pgsql /var/lib/pgsql/10/data
chown postgres:postgres /data -R

/usr/pgsql-10/bin/postgresql-10-setup initdb
echo "listen_addresses '*'" >> /var/lib/pgsql/10/data/postgresql.conf

systemctl enable postgresql-10.service
systemctl start postgresql-10.service
sudo -u postgres psql -U postgres -c 'SHOW config_file'

