#!/bin/bash

set -e

mkfs -t xfs /dev/sdb
mkdir /data
echo "/dev/sdb    /data    xfs    defaults,nofail    0    2" >> /etc/fstab
mount -a

cp mongodb-org-4.0.repo /etc/yum.repos.d/mongodb-org-4.0.repo
yum install -y mongodb-org

mkdir -p /data/mongo
chown mongod:mongod /data -R

rm -f /etc/mongod.conf
cp mongod.conf /etc/mongod.conf

echo "---ADD KEYFILE---" > /data/mongo/keyfile
chmod 600 /data/mongo/keyfile
chown mongod:mongod /data/mongo/keyfile

service mongod start
